name: Build kernel with KernelSU NEXT and SUSFS

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang lld llvm git make gcc flex bison bc libssl-dev ccache libncurses5-dev libncursesw5-dev cmake python3 python-is-python3
      - name: Build Project
        run: | 
          git config --global user.email "you@example.com"
          git config --global user.name "lithneas-github"
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
          
          export KERNEL_REPO="$(pwd)"
          git clone https://gitlab.com/simonpunk/susfs4ksu -b kernel-5.4
          
          curl -k -L https://raw.githubusercontent.com/KhanhNguyen9872/hyperos-kernel-for-renoir/refs/heads/miui-t-hyperos/.github/workflows/0001-Implement-SUSFS-v1.5.3-universal.patch > $KERNEL_REPO/KernelSU-Next/ksunext.patch
          cp $KERNEL_REPO/susfs4ksu/kernel_patches/50_add_susfs_in_kernel-5.4.patch $KERNEL_REPO/
          cp $KERNEL_REPO/susfs4ksu/kernel_patches/fs/* $KERNEL_REPO/fs/
          cp $KERNEL_REPO/susfs4ksu/kernel_patches/include/linux/* $KERNEL_REPO/include/linux/
          
          cd $KERNEL_REPO/KernelSU-Next && patch -p1 < ksunext.patch || echo 'skip error'
          cd $KERNEL_REPO && patch -p1 < 50_add_susfs_in_kernel-5.4.patch || echo 'skip error'

          git add .
          git commit -m "Blump up KSU for NonGKI kernel"
          git status
          chmod +x ./build.sh
          ./build.sh all renoir
      - name: Compress
        run: tar -czvf build.tar.gz ../out/anykernel/Mint*.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar.gz
